server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: Daohaosima1
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.markbackend.pojo
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: log/log.log
  level:
    root: info
    markbackend: debug